FROM ruby:3.1.2-slim AS base

ENV BUNDLER_VERSION=2.3.13 \
    TZ=Asia/Jakarta \
    LANG=C.UTF-8

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends curl gnupg gnupg2 imagemagick openssh-server git python3.10 && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash && \
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    echo "deb http://apt.postgresql.org/pub/repos/apt `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list && \
    apt-get update -qq && \
    apt-get install --no-install-recommends -y  \
            shared-mime-info nodejs build-essential libpq-dev \
            postgresql-client-13 && \
    apt-get clean && \
    corepack enable && \
    rm -rf /var/lib/apt/lists/* && \
    ln -s /usr/bin/python3.10 /usr/bin/python

ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -r blogroll --gid=$GROUP_ID && \
    useradd --create-home -r blogroll -g blogroll --uid=$USER_ID && \
    mkdir -m 755 /blogroll && \
    chown blogroll:blogroll -R /blogroll

WORKDIR /blogroll

COPY docker-entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 3000

########## DEV & TEST IMAGE ##########
FROM base as devtest

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
            build-essential libpq-dev ruby-dev libxml2-dev wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
#     apt-get -f install ./google-chrome-stable_current_amd64.deb && \
#     rm /etc/apt/sources.list.d/google-chrome.list && \
#     rm -rf /var/lib/apt/lists/* /var/cache/apt/* ./google-chrome-stable_current_amd64.deb

RUN curl -sS https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update -qqy \
    && apt-get -qqy install \
    ${CHROME_VERSION:-google-chrome-stable} \
    && rm /etc/apt/sources.list.d/google-chrome.list \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

# RUN apt-get update -qqy && \
#     apt-get install -y libsqlite3-dev

COPY --chown=blogroll:blogroll Gemfile Gemfile.lock package.json yarn.lock /blogroll/

ENV BUNDLE_JOBS=3 \
    BUNDLE_RETRY=3 \
    RAILS_ENV=development \
    REDIS_URL=redis://

RUN gem install bundler:$BUNDLER_VERSION --no-document \
    && bundle config set --local with 'development test' \
    && bundle install \
    && rm -rf /usr/local/bundle/cache/*.gem \
    && find /usr/local/bundle/gems/ -name "*.c" -delete \
    && find /usr/local/bundle/gems/ -name "*.o" -delete

COPY --chown=blogroll:blogroll . /blogroll/
RUN --mount=type=ssh yarn

#Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
